/**
 * `duo setup`: the commands, the agent skills, the Codex allow-rule, and an app launcher, for
 * Linux, macOS and Windows. Everything it writes is listed, and `duo setup --uninstall` removes it.
 */
import { spawn, spawnSync } from 'node:child_process';
import { chmodSync, cpSync, existsSync, lstatSync, mkdirSync, readFileSync, readlinkSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { homedir } from 'node:os';
import { delimiter, dirname, join } from 'node:path';
import { CLAUDE_HOME, CODEX_HOME, PROJECT_ROOT } from './paths.ts';
import { IS_MAC, IS_WIN } from './platform.ts';

type Log = (line: string) => void;

const home = homedir();
const BIN_DIR = join(home, '.local', 'bin');
const CLAUDE_SKILL = join(CLAUDE_HOME, 'skills', 'duo');
const CODEX_SKILL = join(home, '.agents', 'skills', 'duo');
const CODEX_RULE = join(CODEX_HOME, 'rules', 'duo.rules');
const LINUX_DESKTOP = join(process.env.XDG_DATA_HOME || join(home, '.local', 'share'), 'applications', 'duo.desktop');
const MAC_APP = join(home, 'Applications', 'Duo.app');
const WIN_SHORTCUT = join(process.env.APPDATA || join(home, 'AppData', 'Roaming'), 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Duo.lnk');
const WIN_NPM_BIN = join(process.env.APPDATA || join(home, 'AppData', 'Roaming'), 'npm');

/** The Electron binary from duo's own dependencies. */
export function electronBinary(): string {
  const require = createRequire(join(PROJECT_ROOT, 'package.json'));
  const p = require('electron') as unknown;
  if (typeof p !== 'string' || !existsSync(p)) throw new Error('Electron is not installed: run `npm install` in the duo folder');
  return p;
}

const MAIN = () => join(PROJECT_ROOT, 'desktop', 'main.cjs');

/** Open the desktop app, detached from this terminal. */
export function launchGui(): void {
  const child = spawn(electronBinary(), [MAIN()], { detached: true, stdio: 'ignore', windowsHide: false, env: { ...process.env, DUO_NODE: process.execPath } });
  child.unref();
}

function lstatSafe(p: string) {
  try {
    return lstatSync(p);
  } catch {
    return undefined;
  }
}

/** A `duo` or `duo-safe` command link that setup made (from this or another duo checkout), not some other tool's. */
function ourLink(link: string, name: string): boolean {
  try {
    return readlinkSync(link).endsWith(join('bin', `${name}.js`));
  } catch {
    return false;
  }
}

/** A `duo` or `duo-safe` command file on Windows that setup wrote, not another package's. */
function ourWindowsCommand(path: string): boolean {
  try {
    return readFileSync(path, 'utf8').includes('generated by duo setup');
  } catch {
    return false;
  }
}

/** Duo.app as setup writes it: another app may be called Duo too, and it must never be deleted. */
function ourMacApp(): boolean {
  try {
    return readFileSync(join(MAC_APP, 'Contents', 'Info.plist'), 'utf8').includes('<string>dev.duo.app</string>');
  } catch {
    return false;
  }
}

function commands(log: Log): void {
  const targets = [['duo', join(PROJECT_ROOT, 'bin', 'duo.js')], ['duo-safe', join(PROJECT_ROOT, 'bin', 'duo-safe.js')]] as const;
  if (IS_WIN) {
    // npm's global bin folder is on PATH for anyone who installed Node with npm. Like npm, write a
    // .cmd for cmd and PowerShell and an extensionless script for Git Bash, which is the shell Claude
    // Code runs commands in on Windows (the /duo skill's `duo debate ...` runs there).
    mkdirSync(WIN_NPM_BIN, { recursive: true });
    const files = targets.flatMap(([name, target]): [string, string][] => [
      [join(WIN_NPM_BIN, `${name}.cmd`), `@echo off\r\nrem duo (generated by duo setup)\r\nnode "${target}" %*\r\n`],
      [join(WIN_NPM_BIN, name), `#!/bin/sh\n# duo (generated by duo setup)\nexec node '${target.replace(/\\/g, '/').replace(/'/g, `'\\''`)}' "$@"\n`],
    ]);
    for (const [path] of files) if (existsSync(path) && !ourWindowsCommand(path)) throw new Error(`${path} was not written by duo setup; refusing to replace it`);
    for (const [path, text] of files) {
      writeFileSync(path, text);
      log(`wrote ${path}`);
    }
    return;
  }
  mkdirSync(BIN_DIR, { recursive: true });
  for (const [name, target] of targets) {
    const link = join(BIN_DIR, name);
    const st = lstatSafe(link);
    if (st && !st.isSymbolicLink()) throw new Error(`${link} exists and is not a symlink; refusing to replace it`);
    if (st && !ourLink(link, name)) throw new Error(`${link} points to ${readlinkSync(link)}, not duo; refusing to replace it`);
    if (st) rmSync(link);
    symlinkSync(target, link);
    chmodSync(target, 0o755);
    log(`linked ${link} -> ${target}`);
  }
  if (!(process.env.PATH || '').split(delimiter).includes(BIN_DIR)) log(`note: ${BIN_DIR} is not on your PATH; add it to use \`duo\` from a terminal`);
}

function skills(log: Log): void {
  for (const [src, dst] of [[join(PROJECT_ROOT, 'skills', 'claude'), CLAUDE_SKILL], [join(PROJECT_ROOT, 'skills', 'codex'), CODEX_SKILL]] as const) {
    rmSync(dst, { recursive: true, force: true });
    mkdirSync(dirname(dst), { recursive: true });
    cpSync(src, dst, { recursive: true });
    log(`installed skill ${dst}`);
  }
}

function codexRule(log: Log): void {
  const safe = IS_WIN ? join(WIN_NPM_BIN, 'duo-safe.cmd') : join(BIN_DIR, 'duo-safe');
  mkdirSync(dirname(CODEX_RULE), { recursive: true });
  writeFileSync(CODEX_RULE, [
    '# duo: lets Codex run duo-safe (the restricted duo entry point) without an approval prompt.',
    '# duo-safe needs network to reach the model APIs; its seats are read-only, and it refuses raw',
    '# Codex config (cfg:), WebFetch, the GUI, setup, pair mode (also continuing a pair run), apply,',
    '# rm and export -o. The unrestricted `duo` command still asks for approval. Remove with',
    '# `duo setup --uninstall` and restart the Codex app.',
    'prefix_rule(',
    `    pattern = [["duo-safe", ${JSON.stringify(safe)}]],`,
    '    decision = "allow",',
    '    justification = "duo-safe: read-only multi-model session at the user\'s request",',
    '    match = ["duo-safe quota", "duo-safe debate -s claude:opus@high -s codex:gpt-6-sol@high -f brief.md"],',
    '    not_match = ["duo debate -s x", "claude -p hi", "codex exec hi"],',
    ')',
    '',
  ].join('\n'));
  log(`wrote ${CODEX_RULE} (restart the Codex or ChatGPT app to load it)`);
}

/** A PNG inside an ICO container (Windows Vista and later read PNG icons). */
function pngToIco(png: Buffer): Buffer {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(1, 4);
  const entry = Buffer.alloc(16);
  entry.writeUInt8(0, 0); // 0 = 256 px
  entry.writeUInt8(0, 1);
  entry.writeUInt8(0, 2);
  entry.writeUInt8(0, 3);
  entry.writeUInt16LE(1, 4);
  entry.writeUInt16LE(32, 6);
  entry.writeUInt32LE(png.length, 8);
  entry.writeUInt32LE(22, 12);
  return Buffer.concat([header, entry, png]);
}

/** A PNG inside an ICNS container ("ic09" = 512x512). */
function pngToIcns(png: Buffer): Buffer {
  const chunk = Buffer.alloc(8);
  chunk.write('ic09', 0, 'ascii');
  chunk.writeUInt32BE(png.length + 8, 4);
  const head = Buffer.alloc(8);
  head.write('icns', 0, 'ascii');
  head.writeUInt32BE(png.length + 16, 4);
  return Buffer.concat([head, chunk, png]);
}

function launcher(log: Log): void {
  const electron = electronBinary();
  const icon = join(PROJECT_ROOT, 'desktop', 'icon.png');
  if (IS_WIN) {
    const ico = join(PROJECT_ROOT, 'desktop', 'icon.ico');
    if (!existsSync(ico)) writeFileSync(ico, pngToIco(readFileSync(icon)));
    mkdirSync(dirname(WIN_SHORTCUT), { recursive: true });
    const ps = [
      '$s = (New-Object -ComObject WScript.Shell).CreateShortcut($env:DUO_LNK)',
      '$s.TargetPath = $env:DUO_ELECTRON',
      '$s.Arguments = \'"\' + $env:DUO_MAIN + \'"\'',
      '$s.IconLocation = $env:DUO_ICO',
      '$s.Description = "Claude Code and Codex, side by side"',
      '$s.Save()',
    ].join('; ');
    const r = spawnSync('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', ps], { env: { ...process.env, DUO_LNK: WIN_SHORTCUT, DUO_ELECTRON: electron, DUO_MAIN: MAIN(), DUO_ICO: ico }, windowsHide: true, encoding: 'utf8' });
    if (r.status !== 0) throw new Error(`could not create the Start menu shortcut: ${r.stderr || r.error?.message}`);
    log(`created Start menu shortcut ${WIN_SHORTCUT}`);
    return;
  }
  if (IS_MAC) {
    const contents = join(MAC_APP, 'Contents');
    if (existsSync(MAC_APP) && !ourMacApp()) throw new Error(`${MAC_APP} exists and was not created by duo setup; refusing to replace it`);
    rmSync(MAC_APP, { recursive: true, force: true });
    mkdirSync(join(contents, 'MacOS'), { recursive: true });
    mkdirSync(join(contents, 'Resources'), { recursive: true });
    writeFileSync(join(contents, 'Info.plist'), `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>Duo</string>
  <key>CFBundleDisplayName</key><string>Duo</string>
  <key>CFBundleIdentifier</key><string>dev.duo.app</string>
  <key>CFBundleExecutable</key><string>Duo</string>
  <key>CFBundleIconFile</key><string>duo.icns</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSUIElement</key><false/>
</dict></plist>
`);
    const exe = join(contents, 'MacOS', 'Duo');
    writeFileSync(exe, `#!/bin/sh\n# duo launcher (generated by duo setup)\nexec ${JSON.stringify(electron)} ${JSON.stringify(MAIN())} "$@"\n`);
    chmodSync(exe, 0o755);
    writeFileSync(join(contents, 'Resources', 'duo.icns'), pngToIcns(readFileSync(icon)));
    log(`created ${MAC_APP}`);
    return;
  }
  mkdirSync(dirname(LINUX_DESKTOP), { recursive: true });
  writeFileSync(LINUX_DESKTOP, [
    '[Desktop Entry]',
    'Type=Application',
    'Name=Duo',
    'GenericName=Claude and Codex workbench',
    'Comment=Chat with Claude Code and Codex side by side; let them debate, review and pair-program',
    `Exec="${electron}" "${MAIN()}" %U`,
    `Icon=${icon}`,
    'Terminal=false',
    'Categories=Development;',
    'Keywords=AI;Claude;Codex;ChatGPT;agent;',
    'StartupWMClass=Duo',
    '',
  ].join('\n'));
  log(`installed app launcher ${LINUX_DESKTOP} (find “Duo” in the application menu)`);
}

export function install(log: Log, o: { launcher?: boolean } = {}): void {
  commands(log);
  skills(log);
  codexRule(log);
  if (o.launcher !== false) {
    try {
      launcher(log);
    } catch (e) {
      log(`skipped the app launcher: ${(e as Error).message}`);
    }
  }
}

export function uninstall(log: Log): void {
  const removed = (p: string) => log(`removed ${p}`);
  if (IS_WIN) {
    for (const name of ['duo', 'duo-safe']) {
      for (const path of [join(WIN_NPM_BIN, `${name}.cmd`), join(WIN_NPM_BIN, name)]) {
        if (ourWindowsCommand(path)) {
          rmSync(path);
          removed(path);
        }
      }
    }
  } else {
    for (const name of ['duo', 'duo-safe']) {
      const link = join(BIN_DIR, name);
      if (lstatSafe(link)?.isSymbolicLink() && ourLink(link, name)) {
        rmSync(link);
        removed(link);
      }
    }
  }
  for (const p of [CLAUDE_SKILL, CODEX_SKILL, CODEX_RULE, LINUX_DESKTOP, MAC_APP, WIN_SHORTCUT]) {
    if (p === MAC_APP && !ourMacApp()) continue;
    if (existsSync(p)) {
      rmSync(p, { recursive: true, force: true });
      removed(p);
    }
  }
  log('restart the Codex or ChatGPT app so it drops the rule');
}

export const SETUP_PATHS = { BIN_DIR, CLAUDE_SKILL, CODEX_SKILL, CODEX_RULE, LINUX_DESKTOP, MAC_APP, WIN_SHORTCUT };
